#!/usr/bin/env bash
containers=`docker ps -a -q -f status=exited | xargs`
if [[ $containers ]]; then
  docker rm $containers
else
  echo "No containers to remove"
fi

volumes=`docker volume ls -q | xargs`
if [[ $volumes ]]; then
  docker volume rm $volumes
else
  echo "No volumes to remove"
fi

images=`docker images -a -q -f dangling=true | xargs`
if [[ $images ]]; then
  docker rmi $images
else
  echo "No images to remove"
fi

docker images
