#!/bin/bash

# Usage "live command"
# Runs the command, and then any time a file
# in the current directory tree is written to,
# re-runs the command.

function error_exit() { 
  echo "${1}" >&2
  exit 1 
}

clear
$@

case "$(uname -s)" in
  Linux)
    which inotifywait >/dev/null || error_exit "you need 'inotifywait' command (apt-get install inotify-tools  or similar)"``
    while true; do
      inotifywait -qr -e close_write .
      clear
      $@
    done
    ;;
  Darwin)
    which fswatch >/dev/null || err "you need 'fswatch' command (brew install fswatch)"
    fswatch -k -x . | while read x; do
      if [ $(echo "${x}" | grep -cE Attribute) -eq 0 ]; then
        clear
        $@
      fi
    done
    ;;
  *)
    error_exit "Unknown result from uname -s"
    ;;
esac
