#!/usr/bin/env bash
set -e
if hash brew 2> /dev/null; then
  brew update
  brew upgrade
  brew cleanup
fi
if hash apt-get 2> /dev/null; then
  sudo apt-get -y  update
  sudo apt-get -yf dist-upgrade
  sudo apt-get -y autoremove
  sudo apt-get -y autoclean
  sudo updatedb
fi
